version: '3'
services:
  #traefik:
  #  image: traefik:latest
  #  labels:
  #    - "traefik.http.routers.myauth.rule=HostRegexp(`{host:.+}`)"
  #  network_mode: "host"
  #  ports:
  #    - "80:80" # TODO migrar nginx por traefik
  #    - "8082:8080"
  #  volumes:
  #    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #    - "./traefik-config.yml:/traefik.yml"
  #    - "./traefik-servers.yml:/traefik-servers.yml"
  #    - "./traefik.log:/traefik.log"

  portainer:
    #container_name: portainer
    #image: portainer/portainer-ce:latest # community edition
    image: portainer/portainer-ee:latest # enterprise
    labels:
      #- "traefik.http.services.portainer.loadbalancer.server.port=9443"
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.discovery.mair`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.discovery.mair`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=leresolver"
    restart: unless-stopped
    #ports:
    #  - 8000:8000
    #  - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      npi:

  pihole:
    #container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      #- "8080:80"
      #- "443:443"
    environment:
      TZ: "America/Lima"
      ADMIN_EMAIL: "mario21ic@gmail.com"
      WEBPASSWORD: ${pihole_pass}
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.9
    #networks:
    #  npi:
    #    ipv4_address: 172.20.0.7

  whoogle:
    image: benbusby/whoogle-search:buildx-experimental
    #image: benbusby/whoogle-search
    #container_name: whoogle-search
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    # user debian-tor from tor package
    user: '102'
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    #read_only: true
    labels:
      - "traefik.http.routers.whoogle.rule=Host(`whoogle.discovery.mair`)"
      - "traefik.http.services.whoogle.loadBalancer.server.port=5000"
      - "traefik.enable=true"
    #ports:
    #  - "5000:5000"
    #dns:
    #  - 172.20.0.7
    #  - 192.168.1.10
    tmpfs:
      - /config/:size=10M,uid=102,gid=102,mode=1700
      - /var/lib/tor/:size=10M,uid=102,gid=102,mode=1700
      - /run/tor/:size=1M,uid=102,gid=102,mode=1700
    networks:
      npi:
    #    ipv4_address: 172.20.0.8

  plex:
    image: jaymoulin/plex
    hostname: hellion
    restart: unless-stopped
    network_mode: "host"
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.plex.rule=Host(`plex.discovery.mair`)"
    #  #- "traefik.http.services.plex.loadBalancer.server.port=32400"
    expose:
      - 32400
      - 33400
    volumes:
      - ./usr/share/zoneinfo/America/Lima:/etc/localtime:ro
    #ports:
    #  - 8080:80

  dashy:
    image: lissy93/dashy:latest
    restart: unless-stopped
    labels:
      - "traefik.http.routers.dashy.rule=Host(`dashy.discovery.mair`)"
      #- "traefik.http.services.dashy.loadBalancer.server.port=5000"
      - "traefik.enable=true"
    #ports:
    #  - 8083:80
    volumes:
      - ./dashy-config.yml:/app/public/conf.yml
    networks:
      npi:

volumes:
  portainer_data:

networks:
  mymacvlan:
    driver: macvlan
    driver_opts:
      parent: ${net_name}
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.9/27
  npi:
    driver: bridge
  #  ipam:
  #    config:
  #      - subnet: 172.20.0.0/24
