version: '3'
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - SERVERPORT=51820
      - PEERS=2
      - PEERSDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 52820:52820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 172.20.0.7
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.6

  duckdns:
    image: linuxserver/duckdns
    environment:
      - TZ=America/Lima
      - SUBDOMAINS=mario21ic
      - TOKEN=sasdsadsa
      - LOG_FILE=false
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:v5.7
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "America/Lima"
      ADMIN_EMAIL: "miemail@gmail.com"
      WEBPASSWORD: "clave"
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.7
networks:
  containers:
    ipam:
      config:
        - subnet: 172.20.0.0/24
