---
- name: Install Prometheus
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - prometheus
    - prometheus-node-exporter

- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - software-properties-common
    - wget

- name: Add grafana.key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: '0644'
    force: true

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main
    state: present
    filename: grafana

- name: Install Grafana and Promtail
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - grafana
    - promtail
  notify: "restart grafana"


