---
- name: Install UFW
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - ufw

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    #policy: allow
    policy: deny

- name: Set logging
  community.general.ufw:
    logging: 'on'

- community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Deny all access to port 9080
  community.general.ufw:
    rule: deny
    port: '9080'

- name: Deny all access to port 9090
  community.general.ufw:
    rule: deny
    port: '9090'

- name: Deny all access to port 9100
  community.general.ufw:
    rule: deny
    port: '9100'

#- name: Deny everything
#  community.general.ufw:
#    state: enabled
#    policy: deny

